In [1]:
!pip install pandas

Collecting pandas
  Using cached pandas-3.0.1-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\onedrive\documents\desktop\customer_shoping_behaviour\.venv-1\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\onedrive\documents\desktop\customer_shoping_behaviour\.venv-1\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.1-cp313-cp313-win_amd64.whl (9.7 MB)
Downloading numpy-2.4.3-cp313-cp313-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 2.5 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.3 MB 2.1 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.3 MB 2.8 MB/s eta 0:00:04
   --------- ------------------------------ 2.9/12.3 MB 3.3 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.3 MB 3.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.3 MB 3.7 MB/s eta 0:00:03
   ------------------ --------------------- 5.8/12.3 MB 3.8 MB/s eta 0:00:02
   ------------------ --------------------- 5.8/12.3 MB 3.8 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.3 MB 3.5 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.3 MB 3.5 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.3 MB 3.2 MB/s eta 0:00:02
   -------------------------- ------------- 8.1/12.3 MB 3.4 MB/s eta 0:00:02
   --------------------------- ------------ 8.4/12.3 MB 3.0 MB/s eta 0:00:02
   ---------------------------- ----------- 8.9/12.3 MB 3.0 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.3 MB 2.9 MB/s eta 0:00:02
   ------------------------------ --------- 9.4/12.3 MB 2.8 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.3 MB 2.7 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.3 MB 2.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.2/12.3 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.5/12.3 MB 2.4 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 2.4 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 2.2 MB/s eta 0:00:01
   ----------------------------------- ---- 11.0/12.3 MB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 2.1 MB/s eta 0:00:01
   ------------------------------------ --- 11.3/12.3 MB 2.1 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 1.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 1.8 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 1.8 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 1.6 MB/s eta 0:00:00
Using cached tzdata-2025.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [4]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [6]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [7]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [8]:
df['Review Rating']  = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [9]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [10]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')   
df = df.rename(columns={'purchase_amount_(usd)': 'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [12]:
# create a column age_group
labels = [ 'young Adult', 'Adult', 'middle-aged', 'senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [13]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  middle-aged
1   19  young Adult
2   50  middle-aged
3   21  young Adult
4   45  middle-aged
5   46  middle-aged
6   63       senior
7   27  young Adult
8   26  young Adult
9   57  middle-aged

In [14]:
# create a column purches_frequence_day
frequency_mapping = {
    'Fortnightly': 14,
    'weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-weekly': 14  ,  
    'Annually': 365 ,
    'Every 2 months': 60    
}
df['purchase_frequency_day'] = df['frequency_of_purchases'].map(frequency_mapping)

In [15]:
df[['purchase_frequency_day', 'frequency_of_purchases']].head(10)

   purchase_frequency_day frequency_of_purchases
0                    14.0            Fortnightly
1                    14.0            Fortnightly
2                     NaN                 Weekly
3                     NaN                 Weekly
4                   365.0               Annually
5                     NaN                 Weekly
6                    90.0              Quarterly
7                     NaN                 Weekly
8                   365.0               Annually
9                    90.0              Quarterly

In [16]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied']== df['promo_code_used']).all()

np.True_

In [18]:
df = df.drop('promo_code_used', axis = 1)

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_day'],
      dtype='str')

In [20]:
!pip install mysql-connector-python pandas

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: pandas in c:\users\lenovo\onedrive\documents\desktop\customer_shoping_behaviour\.venv-1\lib\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\onedrive\documents\desktop\customer_shoping_behaviour\.venv-1\lib\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\onedrive\documents\desktop\customer_shoping_behaviour\.venv-1\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\onedrive\documents\desktop\customer_shoping_behaviour\.venv-1\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\onedrive\documents\desktop\customer_shoping_behaviour\.venv-1\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading mysql_connector_python-9.6.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
    --------------------------------------- 0.3/16.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/16.5 MB 1.3 MB/s eta 0:00:13
   -- ------------------------------------- 1.0/16.5 MB 1.8 MB/s eta 0:00:09
   --- ------------------------------------ 1.6/16.5 MB 1.9 MB/s eta 0:00:08
   ---- ----------------------------------- 1.8/16.5 MB 2.1 MB/s eta 0:00:08
   ----- ---------------------------------- 2.4/16.5 MB 2.0 MB/s eta 0:00:08
   ------ --------------------------------- 2.6/16.5 MB 2.0 MB/s eta 0:00:07
   ------ --------------------------------- 2.6/16.5 MB 2.0 MB/s eta 0:00:07
   ------ --------------------------------- 2.6/16.5 MB 2.0 MB/s eta 0:00:07
   ------- -------------------------------- 3.1/16.5 MB 1.5 MB/s eta 0:00:09
   ------- -------------------------------- 3.1/16.5 MB 1.5 MB/s eta 0:00:09
   -------- ------------------------------- 3.4/16.5 MB 1.4 MB/s eta 0:00:10
   -------- ------------------------------- 3.4/16.5 MB 1.4 MB/s eta 0:00:10
   -------- ------------------------------- 3.7/16.5 MB 1.3 MB/s eta 0:00:10
   -------- ------------------------------- 3.7/16.5 MB 1.3 MB/s eta 0:00:10
   --------- ------------------------------ 3.9/16.5 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.9/16.5 MB 1.2 MB/s eta 0:00:11
   --------- ------------------------------ 3.9/16.5 MB 1.2 MB/s eta 0:00:11
   ---------- ----------------------------- 4.2/16.5 MB 1.1 MB/s eta 0:00:12
   ---------- ----------------------------- 4.5/16.5 MB 1.1 MB/s eta 0:00:12
   ----------- ---------------------------- 4.7/16.5 MB 1.1 MB/s eta 0:00:12
   ----------- ---------------------------- 4.7/16.5 MB 1.1 MB/s eta 0:00:12
   ------------ --------------------------- 5.0/16.5 MB 1.0 MB/s eta 0:00:12
   ------------ --------------------------- 5.2/16.5 MB 1.0 MB/s eta 0:00:12
   ------------ --------------------------- 5.2/16.5 MB 1.0 MB/s eta 0:00:12
   ------------- -------------------------- 5.5/16.5 MB 1.0 MB/s eta 0:00:11
   ------------- -------------------------- 5.5/16.5 MB 1.0 MB/s eta 0:00:11
   ------------- -------------------------- 5.8/16.5 MB 986.4 kB/s eta 0:00:11
   -------------- ------------------------- 6.0/16.5 MB 973.5 kB/s eta 0:00:11
   -------------- ------------------------- 6.0/16.5 MB 973.5 kB/s eta 0:00:11
   --------------- ------------------------ 6.3/16.5 MB 965.3 kB/s eta 0:00:11
   --------------- ------------------------ 6.3/16.5 MB 965.3 kB/s eta 0:00:11
   --------------- ------------------------ 6.6/16.5 MB 945.1 kB/s eta 0:00:11
   ---------------- ----------------------- 6.8/16.5 MB 944.0 kB/s eta 0:00:11
   ----------------- ---------------------- 7.1/16.5 MB 944.4 kB/s eta 0:00:10
   ----------------- ---------------------- 7.1/16.5 MB 944.4 kB/s eta 0:00:10
   ----------------- ---------------------- 7.3/16.5 MB 930.0 kB/s eta 0:00:10
   ----------------- ---------------------- 7.3/16.5 MB 930.0 kB/s eta 0:00:10
   ------------------ --------------------- 7.6/16.5 MB 932.2 kB/s eta 0:00:10
   ------------------- -------------------- 7.9/16.5 MB 935.6 kB/s eta 0:00:10
   ------------------- -------------------- 8.1/16.5 MB 934.0 kB/s eta 0:00:09
   ------------------- -------------------- 8.1/16.5 MB 934.0 kB/s eta 0:00:09
   ------------------- -------------------- 8.1/16.5 MB 934.0 kB/s eta 0:00:09
   -------------------- ------------------- 8.4/16.5 MB 911.6 kB/s eta 0:00:09
   -------------------- ------------------- 8.7/16.5 MB 916.9 kB/s eta 0:00:09
   --------------------- ------------------ 8.9/16.5 MB 909.8 kB/s eta 0:00:09
   --------------------- ------------------ 8.9/16.5 MB 909.8 kB/s eta 0:00:09
   --------------------- ------------------ 8.9/16.5 MB 909.8 kB/s eta 0:00:09
   ---------------------- ----------------- 9.2/16.5 MB 886.2 kB/s eta 0:00:09
   ---------------------- ----------------- 9.2/16.5 MB 886.2 kB/s eta 0:00:09
   ---------------------- ----------------- 9.4/16.5 MB 875.1 kB/s eta 0:00:09
   ---------------------- ----------------- 9.4/16.5 MB 875.1 kB/s eta 0:00:09
   ----------------------- ---------------- 9.7/16.5 MB 860.3 kB/s eta 0:00:08
   ----------------------- ---------------- 9.7/16.5 MB 860.3 kB/s eta 0:00:08
   ------------------------ --------------- 10.0/16.5 MB 856.8 kB/s eta 0:00:08
   ------------------------ --------------- 10.0/16.5 MB 856.8 kB/s eta 0:00:08
   ------------------------ --------------- 10.0/16.5 MB 856.8 kB/s eta 0:00:08
   ------------------------ --------------- 10.2/16.5 MB 839.1 kB/s eta 0:00:08
   ------------------------ --------------- 10.2/16.5 MB 839.1 kB/s eta 0:00:08
   ------------------------ --------------- 10.2/16.5 MB 839.1 kB/s eta 0:00:08
   ------------------------- -------------- 10.5/16.5 MB 818.4 kB/s eta 0:00:08
   ------------------------- -------------- 10.5/16.5 MB 818.4 kB/s eta 0:00:08
   ------------------------- -------------- 10.5/16.5 MB 818.4 kB/s eta 0:00:08
   -------------------------- ------------- 10.7/16.5 MB 793.0 kB/s eta 0:00:08
   -------------------------- ------------- 10.7/16.5 MB 793.0 kB/s eta 0:00:08
   -------------------------- ------------- 10.7/16.5 MB 793.0 kB/s eta 0:00:08
   -------------------------- ------------- 10.7/16.5 MB 793.0 kB/s eta 0:00:08
   -------------------------- ------------- 10.7/16.5 MB 793.0 kB/s eta 0:00:08
   -------------------------- ------------- 11.0/16.5 MB 750.0 kB/s eta 0:00:08
   -------------------------- ------------- 11.0/16.5 MB 750.0 kB/s eta 0:00:08
   -------------------------- ------------- 11.0/16.5 MB 750.0 kB/s eta 0:00:08
   -------------------------- ------------- 11.0/16.5 MB 750.0 kB/s eta 0:00:08
   --------------------------- ------------ 11.3/16.5 MB 726.7 kB/s eta 0:00:08
   --------------------------- ------------ 11.3/16.5 MB 726.7 kB/s eta 0:00:08
   --------------------------- ------------ 11.3/16.5 MB 726.7 kB/s eta 0:00:08
   --------------------------- ------------ 11.5/16.5 MB 716.9 kB/s eta 0:00:07
   --------------------------- ------------ 11.5/16.5 MB 716.9 kB/s eta 0:00:07
   ---------------------------- ----------- 11.8/16.5 MB 717.4 kB/s eta 0:00:07
   ---------------------------- ----------- 11.8/16.5 MB 717.4 kB/s eta 0:00:07
   ----------------------------- ---------- 12.1/16.5 MB 711.1 kB/s eta 0:00:07
   ----------------------------- ---------- 12.1/16.5 MB 711.1 kB/s eta 0:00:07
   ----------------------------- ---------- 12.1/16.5 MB 711.1 kB/s eta 0:00:07
   ----------------------------- ---------- 12.1/16.5 MB 711.1 kB/s eta 0:00:07
   ----------------------------- ---------- 12.3/16.5 MB 688.6 kB/s eta 0:00:07
   ----------------------------- ---------- 12.3/16.5 MB 688.6 kB/s eta 0:00:07
   ----------------------------- ---------- 12.3/16.5 MB 688.6 kB/s eta 0:00:07
   ----------------------------- ---------- 12.3/16.5 MB 688.6 kB/s eta 0:00:07
   ------------------------------ --------- 12.6/16.5 MB 672.2 kB/s eta 0:00:06
   ------------------------------ --------- 12.6/16.5 MB 672.2 kB/s eta 0:00:06
   ------------------------------ --------- 12.6/16.5 MB 672.2 kB/s eta 0:00:06
   ------------------------------ --------- 12.6/16.5 MB 672.2 kB/s eta 0:00:06
   ------------------------------ --------- 12.6/16.5 MB 672.2 kB/s eta 0:00:06
   ------------------------------- -------- 12.8/16.5 MB 653.9 kB/s eta 0:00:06
   ------------------------------- -------- 12.8/16.5 MB 653.9 kB/s eta 0:00:06
   ------------------------------- -------- 12.8/16.5 MB 653.9 kB/s eta 0:00:06
   ------------------------------- -------- 13.1/16.5 MB 639.9 kB/s eta 0:00:06
   ------------------------------- -------- 13.1/16.5 MB 639.9 kB/s eta 0:00:06
   ------------------------------- -------- 13.1/16.5 MB 639.9 kB/s eta 0:00:06
   ------------------------------- -------- 13.1/16.5 MB 639.9 kB/s eta 0:00:06
   ------------------------------- -------- 13.1/16.5 MB 639.9 kB/s eta 0:00:06
   ------------------------------- -------- 13.1/16.5 MB 639.9 kB/s eta 0:00:06
   -------------------------------- ------- 13.4/16.5 MB 615.0 kB/s eta 0:00:06
   -------------------------------- ------- 13.4/16.5 MB 615.0 kB/s eta 0:00:06
   -------------------------------- ------- 13.4/16.5 MB 615.0 kB/s eta 0:00:06
   -------------------------------- ------- 13.4/16.5 MB 615.0 kB/s eta 0:00:06
   -------------------------------- ------- 13.4/16.5 MB 615.0 kB/s eta 0:00:06
   -------------------------------- ------- 13.4/16.5 MB 615.0 kB/s eta 0:00:06
   -------------------------------- ------- 13.4/16.5 MB 615.0 kB/s eta 0:00:06
   --------------------------------- ------ 13.6/16.5 MB 588.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.6/16.5 MB 588.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.6/16.5 MB 588.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.6/16.5 MB 588.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.6/16.5 MB 588.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.6/16.5 MB 588.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.6/16.5 MB 588.1 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.5 MB 562.4 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.5 MB 562.4 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.5 MB 562.4 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.5 MB 562.4 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.5 MB 562.4 kB/s eta 0:00:05
   --------------------------------- ------ 13.9/16.5 MB 562.4 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 545.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 545.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 545.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 545.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 545.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 545.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.2/16.5 MB 545.0 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ---------------------------------- ----- 14.4/16.5 MB 523.7 kB/s eta 0:00:05
   ----------------------------------- ---- 14.7/16.5 MB 504.7 kB/s eta 0:00:04
   ----------------------------------- ---- 14.7/16.5 MB 504.7 kB/s eta 0:00:04
   ----------------------------------- ---- 14.7/16.5 MB 504.7 kB/s eta 0:00:04
   ----------------------------------- ---- 14.7/16.5 MB 504.7 kB/s eta 0:00:04
   ----------------------------------- ---- 14.7/16.5 MB 504.7 kB/s eta 0:00:04
   ------------------------------------ --- 14.9/16.5 MB 494.9 kB/s eta 0:00:04
   ------------------------------------ --- 14.9/16.5 MB 494.9 kB/s eta 0:00:04
   ------------------------------------ --- 14.9/16.5 MB 494.9 kB/s eta 0:00:04
   ------------------------------------ --- 14.9/16.5 MB 494.9 kB/s eta 0:00:04
   ------------------------------------ --- 14.9/16.5 MB 494.9 kB/s eta 0:00:04
   ------------------------------------ --- 15.2/16.5 MB 440.3 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 440.3 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 440.3 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 440.3 kB/s eta 0:00:03
   ------------------------------------ --- 15.2/16.5 MB 440.3 kB/s eta 0:00:03
   ------------------------------------- -- 15.5/16.5 MB 406.9 kB/s eta 0:00:03
   ------------------------------------- -- 15.5/16.5 MB 406.9 kB/s eta 0:00:03
   ------------------------------------- -- 15.5/16.5 MB 406.9 kB/s eta 0:00:03
   -------------------------------------- - 15.7/16.5 MB 402.6 kB/s eta 0:00:02
   -------------------------------------- - 15.7/16.5 MB 402.6 kB/s eta 0:00:02
   -------------------------------------- - 15.7/16.5 MB 402.6 kB/s eta 0:00:02
   -------------------------------------- - 16.0/16.5 MB 399.9 kB/s eta 0:00:02
   -------------------------------------- - 16.0/16.5 MB 399.9 kB/s eta 0:00:02
   ---------------------------------------  16.3/16.5 MB 403.9 kB/s eta 0:00:01
   ---------------------------------------  16.3/16.5 MB 403.9 kB/s eta 0:00:01
   ---------------------------------------  16.5/16.5 MB 395.7 kB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 394.6 kB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
!pip install pymysql sqlalchemy

Collecting pymysql
  Using cached pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Collecting sqlalchemy
  Using cached sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.3.2-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Using cached pymysql-1.1.2-py3-none-any.whl (45 kB)
Using cached sqlalchemy-2.0.48-cp313-cp313-win_amd64.whl (2.1 MB)
Using cached greenlet-3.3.2-cp313-cp313-win_amd64.whl (230 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, pymysql, greenlet, sqlalchemy

   ---------------------------------------- 0/4 [typing-extensions]
   ---------- ----------------------------- 1/4 [pymysql]
   ---------- ----------------------------- 1/4 [pymysql]
   ---------- ----------------------------- 1/4 [pymysql]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   -------------------- ------------------- 2/4 [greenlet]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ------------------------------ --------- 3/4 [sqlalchemy]
   ---------------------------------------- 4/4 [sqlalchemy]

Successfully installed greenlet-3.3.2 pymysql-1.1.2 sqlalchemy-2.0.48 typing-extensions-4.15.0

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
from sqlalchemy import create_engine

In [30]:
# MySQL connection details
username = "root"
password = "MYSQL@8050"
host = "localhost"
port = "3306"
database = "mydatabase"

# Create connection engine
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:MYSQL%408050@localhost:3306/customer"
)

# Write DataFrame to MySQL
table_name = "customers"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print("Data successfully written to MySQL!")

Data successfully written to MySQL!